name: Update Pure Source
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 升级到 v4
        
      - name: Set up Python
        uses: actions/setup-python@v5 # 升级到 v5
        with:
          python-version: '3.11'
          
      - name: Run Clean Script
        run: |
          pip install requests
          python clean.py
          
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add pure_source.json
          git commit -m "Update pure source" || exit 0
          git push
